# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Wallace group
author: Chris Wallace
email: cew54-at-cam-dot-ac-dot-uk
description: >- # this means to ignore newlines until "baseurl:"
  <b>Statistics</b> applied to genomics to understand autoimmune diseases
baseurl: # the subpath of your site, e.g. /blog
url: http://chr1swallace.github.io # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: chr1swallace
github_username:  chr1swallace
orcid_id: 0000-0001-9755-1703

# Build settings
markdown: kramdown
#theme: starving-artist-jekyll-theme
theme: minima
plugins:
  - jekyll-feed
collections:
  group:
    output: true
    permalink: /group/:path/
  research:
    output: true
    permalink: /research/:path/
sass:
    sass_dir: _sass
  
# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude: [Rakefile]
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/


# Other options
permalink: blog/:year/:month/:title
show_excerpts: true

scholar:
  bibliography_template: altbib
  last_name: Wallace
  style: science
  relative: "/papers/index.html"

## octopress
# Default extension for new posts and pages
post_ext: md
page_ext: html

# Default templates for posts and pages
# Found in _templates/
post_layout: post
page_layout: page

# Format titles with titlecase?
titlecase: true

# Change default template file (in _templates/)
post_template: post
page_template: page
draft_template: draft
